Unterstützung mehrerer Java-Versionen hinzugefügt
theSimpleCloud/SimpleCloud pull request #69
Opened 2022-05-31 15:42 UTC by Mischmaschine

Bei dem Erstellen eines neuen Services (`Server-Group`, `Lobby-Group`) kann man nun eine Java-Version, von der dann der zuvor konfigurierte Java-Command benutzt wird, spezifizieren. Im Setup, das beim ersten Start der Cloud ausgeführt wird, kann man dann seine Java-Commands setzten oder auch einfach "java" angeben, um die vom Server aus aktuelle default Java-Version zu nutzen. Außerdem habe ich in dem Notfiy-Modul zwei neue Placeholder (`%WRAPPER%`, `%CPUUSAGE%`) hinzugefügt, die logischerweise den Wrapper und die dazugehörige CPU-Usage zurück geben.

2022-06-02 21:05 UTC, FllipEis requested changes

2022-06-02 21:05 UTC, FllipEis commented on simplecloud-base/src/main/kotlin/eu/thesimplecloud/base/manager/setup/provider/ServiceJavaCommandAnswerProvider.kt
> +        return JavaVersion.paths.versions.keys.union(listOf("default"))
Für was ist das `default`? 
Das wird doch eh nur ausgeführt, wenn es konfigurierte Javaversionen gibt.

2022-06-06 14:52 UTC, Mischmaschine commented on build.gradle
> +    version '2.3.0'
✓

2022-06-06 15:08 UTC, ClientDNS commented on build.gradle
> +    version '2.3.0'
✓

2022-06-06 15:10 UTC, FllipEis approved these changes
👍

2022-06-06 15:11 UTC, merged