Feature/new reload command
theSimpleCloud/SimpleCloud pull request #97
Opened 2022-12-15 17:39 UTC by D151l

2022-12-16 12:57 UTC, FllipEis requested changes

2022-12-16 12:57 UTC, FllipEis commented on simplecloud-base/src/main/kotlin/eu/thesimplecloud/base/manager/commands/ReloadCommand.kt
> +    }
Please add a message

2022-12-16 12:57 UTC, FllipEis commented on simplecloud-base/src/main/kotlin/eu/thesimplecloud/base/manager/commands/ReloadCommand.kt
> +    }
Please add a message

2022-12-16 12:57 UTC, FllipEis commented on simplecloud-base/src/main/kotlin/eu/thesimplecloud/base/manager/commands/ReloadCommand.kt
> +    }
Please add a message

2022-12-16 12:57 UTC, FllipEis commented on simplecloud-base/src/main/kotlin/eu/thesimplecloud/base/manager/commands/ReloadCommand.kt
> +    }
Please add a message

2022-12-16 12:57 UTC, FllipEis commented on simplecloud-base/src/main/kotlin/eu/thesimplecloud/base/manager/commands/ReloadCommand.kt
>      }
Please add a message

2022-12-17 10:36 UTC, D151l commented
The missing messages are already sent elsewhere in the cloud, so I don't need to insert additional messages.

2022-12-17 10:57 UTC, FllipEis approved these changes

2022-12-17 10:58 UTC, merged